# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Ressources STI2D SIN et NSI
site_description: Cours de STI2D SIN et de NSI
site_author: Christopher CHAMAND

docs_dir: docs

nav:
    - "Accueil": index.md
    - "STI2D": sti2d.md
    - "NSI": nsi.md

theme:
    name: material
    language: fr                    # français

    palette:
        scheme: default
        primary: brown
        accent: orange
